<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sector Population Report</title>
    <style>
        body {
            font-family: 'Times New Roman', Times, serif;
            font-size: 14px;
            background: #fff;
            color: #000;
            margin: 0;
            padding: 20px;
            line-height: 1.5;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
            margin-bottom: 20px;
            position: relative;
        }
        .header h1 {
            font-size: 18px;
            font-weight: bold;
            margin: 5px 0;
        }
        .header p {
            margin: 0;
            font-size: 13px;
        }
        .header img {
            max-width: 80px;
            max-height: 80px;
            object-fit: contain;
        }
        .logo-left {
            position: absolute;
            left: 0;
            top: 0;
        }
        .logo-right {
            position: absolute;
            right: 0;
            top: 0;
        }
        .report-title {
            text-align: center;
            font-size: 20px;
            font-weight: bold;
            margin-bottom: 25px;
            text-transform: uppercase;
        }
        .filters {
            margin-bottom: 20px;
            padding: 10px;
            background: #f2f2f2;
            border: 1px solid #ccc;
        }
        .filter-item {
            margin: 4px 0;
            font-size: 13px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            margin-bottom: 30px;
        }
        th, td {
            border: 1px solid #333;
            padding: 6px 10px;
            font-size: 13px;
            text-align: left;
        }
        th {
            background: #d9d9d9;
        }
        .footer {
            margin-top: 40px;
            text-align: right;
            font-size: 12px;
            color: #666;
        }
        @page {
            size: A4;
            margin: 15mm;
        }
        @media print {
            .no-print {
                display: none;
            }
            body {
                margin: 0;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        @if($barangayDetails)
            @if($barangayDetails->logo1_path ?? $barangayDetails->barangay_logo)
                <img src="{{ asset('storage/' . ($barangayDetails->logo1_path ?? $barangayDetails->barangay_logo)) }}" class="logo-left">
            @endif
            @if($barangayDetails->logo2_path)
                <img src="{{ asset('storage/' . $barangayDetails->logo2_path) }}" class="logo-right">
            @endif
        @endif

        <h1>{{ $barangayDetails->heading1 ?? 'REPUBLIC OF THE PHILIPPINES' }}</h1>
        <h1>{{ $barangayDetails->heading2 ?? ($barangayDetails->province ?? 'PROVINCE') . ', ' . ($barangayDetails->city_municipality ?? 'CITY/MUNICIPALITY') }}</h1>
        <h1>{{ $barangayDetails->heading3 ?? ($barangayDetails->barangay_name ?? 'BARANGAY') }}</h1>
        <div class="report-title">
            SECTOR POPULATION REPORT: {{ strtoupper(str_replace('_', ' ', $sectorType)) }}
        </div>
        <p>Generated on: {{ now()->format('F j, Y h:i A') }}</p>
    </div>

    <div class="filters">
        <h3 style="margin-top: 0;">Report Filters</h3>
        <div class="filter-item"><strong>Sector Type:</strong> {{ strtoupper(str_replace('_', ' ', $sectorType)) }}</div>
        <div class="filter-item"><strong>Total Records:</strong> {{ $residents->count() }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Address</th>
                <th>Occupation/Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($residents as $index => $resident)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $resident->last_name }}, {{ $resident->first_name }} {{ $resident->middle_name }}</td>
                <td>{{ $resident->age }}</td>
                <td>{{ $resident->sex }}</td>
                <td>{{ $resident->purok ? $resident->purok->purok_name : $resident->address }}</td>
                <td>
                    @if($sectorType === 'labor_force' || $sectorType === 'unemployed' || $sectorType === 'ofw')
                        {{ $resident->occupation ?? 'N/A' }}
                    @elseif($sectorType === 'out_of_school_children' || $sectorType === 'out_of_school_youth')
                        {{ $resident->education_status ?? 'Not enrolled' }}
                    @else
                        N/A
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by iBarangay System</p>
    </div>

    <script>
        window.onload = function() {
            window.print();
        }
         window.onafterprint = function() {
            window.close();
        };
    </script>
</body>
</html>